# Generated by Django 5.0.2 on 2025-05-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='custom_html',
            field=models.TextField(blank=True, help_text='Enter the HTML content for the book page'),
        ),
    ]
