# Generated by Django 5.0.2 on 2025-05-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_custom_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='custom_html',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
