# Generated by Django 5.0.2 on 2025-05-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='unique_visitor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['ip_address', 'unique_visitor'], name='books_visit_ip_addr_5b11e9_idx'),
        ),
    ]
